### ISSUE TITLE
Reading custom fields

### ISSUE THREAD

**Issue by ghost** [techtalk/JiraRestClient#37]
Hi,

is reading custom fields a supported feature?
If not, are there any plans for it?

Best regards

**Comment by quexy** [comment]
already supported; see: https://gist.github.com/quexy/9183880

**Comment by ghost** [comment]
Am I missing something? The gist shows how to write custom fields, but I don't see reading custom fields.

**Comment by quexy** [comment]
Yes, you are. Reading fields is analogous. If you can write a custom field `customfield_10010` through `JiraClient<MyIssueFields>`, then, I'd suspect, you could surely read the same field.

In the terminology of the gist:

```
var issueY = clientX.LoadIssue(issue);
System.Diagnostics.Assert(issueX.customfield_10010 == issueY.customfield_10010, "Oops...");
```
