### ISSUE TITLE
How to get field fixVersion?

### ISSUE THREAD

**Issue by Oleksandr-Silin** [techtalk/JiraRestClient#42]
passing "new string[2] {"status", "fixVersion" }" to EnumerateIssuesByQuery does not help. And I can't find any documentation for library. Thanks for help!

**Comment by quexy** [comment]
You have to use a custom issue fields type

**Comment by Oleksandr-Silin** [comment]
How? any documentation, examples?

**Comment by quexy** [comment]
No docs; be smart. Hint: `MyIssueFields : IssueFields { public string fixVersion { get; set; } }`
