### ISSUE TITLE
Get custom fields in GetIssuesByQuery

### ISSUE THREAD

**Issue by heymanitsmematt** [techtalk/JiraRestClient#43]
Is there a way to get custom fields? It seems like the properties exposed in TIssueFields are basically what you get when interacting with an Issue.fields object. Are there any plans to incorporate custom fields? Maybe allow users to hardcode them? I cloned a copy of master and hard coded my own project's custom fields for a Netsuite integration, but this option is less than ideal when users could simply push an array of custom fields to populate.

**Comment by Anastasius80** [comment]
I used it hardcoded, but it works perfekt:

```
    [DeserializeAs(Name = "customfield_10502")]
    public int SerialNumber { get; set; }
```

**Comment by quexy** [comment]
Just extend IssueFields and use JiraClient with that type, like @Anastasius80 suggested.
